const admin=require('firebase-admin');
const crypto=require('crypto');
function getAdminApp(){if(admin.apps.length)return admin.app();let s;if(process.env.FIREBASE_SERVICE_ACCOUNT_JSON)s=JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON);else{const{FIREBASE_PROJECT_ID,FIREBASE_CLIENT_EMAIL,FIREBASE_PRIVATE_KEY}=process.env;if(!FIREBASE_PROJECT_ID||!FIREBASE_CLIENT_EMAIL||!FIREBASE_PRIVATE_KEY)throw new Error('Firebase Admin environment variables are not configured.');s={projectId:FIREBASE_PROJECT_ID,clientEmail:FIREBASE_CLIENT_EMAIL,privateKey:FIREBASE_PRIVATE_KEY.replace(/\\n/g,'\n')}}return admin.initializeApp({credential:admin.credential.cert(s)})}
function reply(res,status,body){res.setHeader('Cache-Control','no-store');return res.status(status).json(body)}
function b64url(v){return Buffer.from(v).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function googleAccessToken(){const raw=process.env.GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON;if(!raw)throw new Error('GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON is not configured.');const sa=JSON.parse(raw);const now=Math.floor(Date.now()/1000);const header=b64url(JSON.stringify({alg:'RS256',typ:'JWT'}));const claim=b64url(JSON.stringify({iss:sa.client_email,scope:'https://www.googleapis.com/auth/drive.file',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));const signer=crypto.createSign('RSA-SHA256');signer.update(`${header}.${claim}`);const signature=b64url(signer.sign(sa.private_key));const jwt=`${header}.${claim}.${signature}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})});const d=await r.json();if(!r.ok||!d.access_token)throw new Error('Unable to obtain Google Drive access token.');return d.access_token}
module.exports=async function handler(req,res){
 if(req.method==='GET' && String(req.query?.action||'')==='list'){
  try{const school=String(req.query?.school||'').trim();if(!school)return reply(res,400,{ok:false,error:'Choose a school before loading listings.'});const app=getAdminApp();const snap=await admin.firestore(app).collection('publishedListings').where('school','==',school).limit(300).get();const listings=[];snap.forEach(doc=>{const d=doc.data()||{};if(d.published===true)listings.push({id:doc.id,...d,createdAt:d.createdAt?.toDate?.()?.toISOString?.()||null,updatedAt:d.updatedAt?.toDate?.()?.toISOString?.()||null});});listings.sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')));return reply(res,200,{ok:true,school,listings})}catch(e){console.error('Published listings read error',e);return reply(res,500,{ok:false,error:'Unable to load published listings for this school.'})}
 }
 if(req.method!=='POST'){res.setHeader('Allow','POST');return reply(res,405,{ok:false,error:'Method not allowed.'})}
 try{
  const bearer=req.headers.authorization||'';if(!bearer.startsWith('Bearer '))return reply(res,401,{ok:false,error:'Google sign-in is required.'});
  const app=getAdminApp();const decoded=await admin.auth(app).verifyIdToken(bearer.slice(7));const db=admin.firestore(app);const action=String(req.body?.action||'upload');
  if(action==='status'){
    const snap=await db.collection('driveConnections').doc(decoded.uid).get();const d=snap.exists?snap.data():{};return reply(res,200,{ok:true,connected:!!d.connected,connectedAt:d.connectedAt?.toDate?.()?.toISOString?.()||null});
  }
  if(action==='connect'){
    const accessToken=typeof req.body?.accessToken==='string'?req.body.accessToken.trim():'';if(accessToken.length<20||accessToken.length>4096)return reply(res,400,{ok:false,error:'A valid Google Drive authorization token is required.'});
    const probe=await fetch('https://www.googleapis.com/drive/v3/files?pageSize=1&spaces=drive&fields=files(id)',{headers:{Authorization:`Bearer ${accessToken}`}});const driveData=await probe.json().catch(()=>({}));
    if(!probe.ok||!Array.isArray(driveData.files))return reply(res,403,{ok:false,error:'Google Drive authorization could not be verified.'});
    await db.collection('driveConnections').doc(decoded.uid).set({uid:decoded.uid,connected:true,googleEmail:decoded.email||null,connectedAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});
    return reply(res,200,{ok:true,connected:true,email:decoded.email||null});
  }
  const connection=await db.collection('driveConnections').doc(decoded.uid).get();if(!connection.exists||connection.data()?.connected!==true)return reply(res,403,{ok:false,error:'Connect Google Drive before uploading business media.'});
  if(action==='publish'){
    const listing=req.body?.listing||{};
    const required=['businessName','school','category','shortDescription','description','priceFrom','priceRange','address','hours','whatsapp','email','featuredImageUrl'];
    if(required.some(k=>listing[k]===undefined||listing[k]===null||String(listing[k]).trim()===''))return reply(res,400,{ok:false,error:'Complete all required listing information before publishing.'});
    if(listing.confirmed!==true)return reply(res,400,{ok:false,error:'Confirm that the business information is accurate before publishing.'});
    if(!String(listing.featuredImageUrl).startsWith('https://drive.google.com/'))return reply(res,400,{ok:false,error:'Featured image must be stored in CampBiz Google Drive storage.'});
    const images=Array.isArray(listing.productImages)?listing.productImages.filter(Boolean):[];
    if(images.length>100)return reply(res,400,{ok:false,error:'A Pro listing can contain up to 100 product images.'});
    const billing=await db.collection('billingCustomers').doc(decoded.uid).get();const bd=billing.exists?billing.data()||{}:{};const now=Date.now();const trialEnd=bd.trialEndsAt?.toMillis?.()||0;const subEnd=bd.subscriptionEndsAt?.toMillis?.()||0;const active=['active','non_renewing','attention'].includes(String(bd.subscriptionStatus||''))&&subEnd>now;const trialActive=!active&&trialEnd>now;const isPro=active||trialActive||String(bd.plan||bd.selectedPlan||'')==='lifetime';
    if(images.length>7&&!isPro)return reply(res,403,{ok:false,error:'Free listings allow up to 7 product images. Upgrade to Pro for the larger gallery.'});
    const clean={id:`owner_${decoded.uid}`,uid:decoded.uid,businessName:String(listing.businessName).trim().slice(0,80),school:String(listing.school).trim().slice(0,120),category:String(listing.category).trim().slice(0,80),shortDescription:String(listing.shortDescription).trim().slice(0,140),description:String(listing.description).trim().slice(0,1200),priceFrom:Number(listing.priceFrom)||0,priceRange:String(listing.priceRange).trim().slice(0,80),address:String(listing.address).trim().slice(0,180),hours:String(listing.hours).trim().slice(0,180),delivery:String(listing.delivery||'By arrangement').trim().slice(0,120),whatsapp:String(listing.whatsapp).trim().slice(0,40),email:String(listing.email).trim().slice(0,160),website:String(listing.website||'').trim().slice(0,300),featuredImageUrl:String(listing.featuredImageUrl),featuredImageId:listing.featuredImageId||null,productImages:images.slice(0,isPro?100:7),published:true,ownerUid:decoded.uid,updatedAt:admin.firestore.FieldValue.serverTimestamp()};
    const ref=db.collection('publishedListings').doc(clean.id);const old=await ref.get();if(!old.exists)clean.createdAt=admin.firestore.FieldValue.serverTimestamp();await ref.set(clean,{merge:true});return reply(res,200,{ok:true,id:clean.id,publishedAt:new Date().toISOString(),imageCount:clean.productImages.length});
  }
  const folder=process.env.DRIVE_FOLDER_ID||'1--aiQe2xifD9OAA5h2GbSW8FufHcbMaQ';const{fileName,mimeType,data}=req.body||{};if(typeof fileName!=='string'||fileName.length<1||fileName.length>180||typeof mimeType!=='string'||typeof data!=='string')return reply(res,400,{ok:false,error:'fileName, mimeType and base64 data are required.'});
  const cleaned=data.replace(/^data:[^;]+;base64,/,'');const bytes=Buffer.from(cleaned,'base64');const imageMime=/^image\/(jpeg|png|webp)$/i.test(mimeType);const maxBytes=imageMime?550*1024:8*1024*1024;if(!bytes.length||bytes.length>maxBytes)return reply(res,413,{ok:false,error:imageMime?'Image must be compressed to 550 KB or smaller before storage.':'File must be between 1 byte and 8 MB.'});
  const token=await googleAccessToken();const boundary='----CampBiz'+crypto.randomBytes(12).toString('hex');const metadata={name:fileName.replace(/[\\/:*?"<>|]/g,'_'),parents:[folder],description:`CampBiz owner asset · ${decoded.uid}`};const body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: ${mimeType}\r\n\r\n`),bytes,Buffer.from(`\r\n--${boundary}--`)]);
  const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});const result=await r.json().catch(()=>({}));if(!r.ok||!result.id){console.error('Drive upload failed',result);return reply(res,502,{ok:false,error:'Google Drive could not store this file.'})}
  const perm=await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(result.id)}/permissions`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({type:'anyone',role:'reader'})});if(!perm.ok){console.error('Drive public permission failed',await perm.text().catch(()=>''));return reply(res,502,{ok:false,error:'File was stored but could not be made viewable in the feed.'})}
  const publicUrl=`https://drive.google.com/uc?export=view&id=${result.id}`;return reply(res,200,{ok:true,fileId:result.id,name:result.name,mimeType:result.mimeType,webViewLink:result.webViewLink||`https://drive.google.com/file/d/${result.id}/view`,publicUrl});
 }catch(e){console.error('Drive storage error',e);return reply(res,500,{ok:false,error:'Unable to store this file in Google Drive.'})}
}
