const admin=require('firebase-admin');
const {entitlementFromDoc}=require('../_lib/entitlement');
let planCache={at:0,data:null};
async function loadPlans(){if(planCache.data&&Date.now()-planCache.at<3600000)return planCache.data;const secret=process.env.PAYSTACK_SECRET_KEY;if(!secret)return null;const codes={monthly:process.env.PAYSTACK_MONTHLY_PLAN_CODE||'PLN_l3x2lebuzk6dzqw',annual:process.env.PAYSTACK_ANNUAL_PLAN_CODE||'PLN_9b33lqkxewk4hh8'};const out={};try{for(const [k,c] of Object.entries(codes)){const r=await fetch(`https://api.paystack.co/plan/${encodeURIComponent(c)}`,{headers:{Authorization:`Bearer ${secret}`}});const d=await r.json().catch(()=>({}));if(r.ok&&d.status&&d.data)out[k]={amount:Number(d.data.amount||0)/100,interval:d.data.interval||null,currency:d.data.currency||'NGN'}}}catch(e){console.error('Plan lookup failed',e)}if(Object.keys(out).length){planCache={at:Date.now(),data:out};return out}return null}
function getAdminApp(){if(admin.apps.length)return admin.app();let s;if(process.env.FIREBASE_SERVICE_ACCOUNT_JSON)s=JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON);else{const{FIREBASE_PROJECT_ID,FIREBASE_CLIENT_EMAIL,FIREBASE_PRIVATE_KEY}=process.env;if(!FIREBASE_PROJECT_ID||!FIREBASE_CLIENT_EMAIL||!FIREBASE_PRIVATE_KEY)throw new Error('Firebase Admin environment variables are not configured.');s={projectId:FIREBASE_PROJECT_ID,clientEmail:FIREBASE_CLIENT_EMAIL,privateKey:FIREBASE_PRIVATE_KEY.replace(/\\n/g,'\n')}}return admin.initializeApp({credential:admin.credential.cert(s)})}
function reply(res,status,body){res.setHeader('Cache-Control','no-store');return res.status(status).json(body)}
module.exports=async function handler(req,res){
 if(req.method!=='GET'){res.setHeader('Allow','GET');return reply(res,405,{ok:false,error:'Method not allowed.'})}
 try{
  const b=req.headers.authorization||'';if(!b.startsWith('Bearer '))return reply(res,401,{ok:false,error:'Google sign-in is required.'});const app=getAdminApp();const u=await admin.auth(app).verifyIdToken(b.slice(7));if((u.email||'').toLowerCase()==='ilemobayotolulope11092003@gmail.com')return reply(res,200,{ok:true,active:true,free:true,locked:false,plan:'lifetime'});
  const ref=admin.firestore(app).collection('billingCustomers').doc(u.uid);const snap=await ref.get();let d=snap.exists?snap.data():{};const now=Date.now();
  if(!d.trialStartedAt&&!d.subscriptionStatus){const start=new Date(now),trialEnd=new Date(start);trialEnd.setMonth(trialEnd.getMonth()+2);d={...d,uid:u.uid,email:u.email||null,provider:'paystack',trialStartedAt:admin.firestore.Timestamp.fromDate(start),trialEndsAt:admin.firestore.Timestamp.fromDate(trialEnd),updatedAt:admin.firestore.FieldValue.serverTimestamp()};await ref.set(d,{merge:true})}
  const end=d.subscriptionEndsAt?.toMillis?d.subscriptionEndsAt.toMillis():0;const trialEnd=d.trialEndsAt?.toMillis?d.trialEndsAt.toMillis():0;const status=String(d.subscriptionStatus||'');const active=['active','non_renewing','attention'].includes(status)&&end>now;const trialActive=!active&&trialEnd>now;const ent=entitlementFromDoc(d,now);const plans=ent.entitled?null:await loadPlans();return reply(res,200,{ok:true,active,trialActive,locked:!ent.entitled,plans,trialEndsAt:trialEnd?new Date(trialEnd).toISOString():null,trialBillingReady:!!d.trialBillingReady,plan:d.plan||d.selectedPlan||null,subscriptionStatus:status||null,subscriptionEndsAt:end?new Date(end).toISOString():null,paystackSubscriptionCode:d.paystackSubscriptionCode||null})
 }catch(e){console.error('Subscription status error',e);return reply(res,500,{ok:false,error:'Unable to load subscription status.'})}
};
