const admin=require('firebase-admin');
function getAdminApp(){if(admin.apps.length)return admin.app();let s;if(process.env.FIREBASE_SERVICE_ACCOUNT_JSON)s=JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON);else{const{FIREBASE_PROJECT_ID,FIREBASE_CLIENT_EMAIL,FIREBASE_PRIVATE_KEY}=process.env;if(!FIREBASE_PROJECT_ID||!FIREBASE_CLIENT_EMAIL||!FIREBASE_PRIVATE_KEY)throw new Error('Firebase Admin environment variables are not configured.');s={projectId:FIREBASE_PROJECT_ID,clientEmail:FIREBASE_CLIENT_EMAIL,privateKey:FIREBASE_PRIVATE_KEY.replace(/\\n/g,'\n')}}return admin.initializeApp({credential:admin.credential.cert(s)})}
function reply(res,status,body){res.setHeader('Cache-Control','no-store');return res.status(status).json(body)}
module.exports=async function handler(req,res){
 if(req.method!=='POST'){res.setHeader('Allow','POST');return reply(res,405,{ok:false,error:'Method not allowed.'})}
 try{
  const b=req.headers.authorization||'';if(!b.startsWith('Bearer '))return reply(res,401,{ok:false,error:'Google sign-in is required.'});const app=getAdminApp();const decoded=await admin.auth(app).verifyIdToken(b.slice(7));const reference=String(req.body?.reference||'');
  if(!/^[A-Za-z0-9_-]{8,80}$/.test(reference))return reply(res,400,{ok:false,error:'Invalid payment reference.'});const db=admin.firestore(app);const paymentRef=db.collection('subscriptionPayments').doc(reference);const snap=await paymentRef.get();if(!snap.exists||snap.data().uid!==decoded.uid)return reply(res,404,{ok:false,error:'Payment was not found.'});const p=snap.data();
  if(p.status==='tokenization_verified')return reply(res,200,{ok:true,enrolled:true,message:'Billing is already enrolled.'});
  const secret=process.env.PAYSTACK_SECRET_KEY;if(!secret)return reply(res,503,{ok:false,error:'Paystack secret key is not configured.'});const r=await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`,{headers:{Authorization:`Bearer ${secret}`}});const d=await r.json().catch(()=>({}));const tx=d.data||{};
  if(!r.ok||!d.status||tx.status!=='success'||String(tx.currency||'').toUpperCase()!=='NGN'||Number(tx.amount)!==5000)return reply(res,400,{ok:false,error:'The refundable card verification could not be verified.'});
  const auth=tx.authorization||{};if(!auth.authorization_code||auth.reusable!==true)return reply(res,400,{ok:false,error:'This payment method cannot be used for recurring billing. Please try another card.'});
  const refund=await fetch('https://api.paystack.co/refund',{method:'POST',headers:{Authorization:`Bearer ${secret}`,'Content-Type':'application/json'},body:JSON.stringify({transaction:reference,amount:5000,currency:'NGN',merchant_note:'CampBiz refundable card verification for free trial',customer_note:'CampBiz card verification refund'})});const rd=await refund.json().catch(()=>({}));
  const existing=(await db.collection('billingCustomers').doc(decoded.uid).get()).data()||{};
  await db.collection('billingCustomers').doc(decoded.uid).set({uid:decoded.uid,email:decoded.email||null,provider:'paystack',trialBillingReady:true,authorizationCode:auth.authorization_code,authorizationSignature:auth.signature||null,paystackCustomerCode:tx.customer?.customer_code||null,selectedPlan:p.plan||'monthly',plan:p.plan||'monthly',trialTokenizationReference:reference,trialTokenizationRefundStatus:refund.ok&&rd.status?'queued':'failed',updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});
  await paymentRef.set({status:'tokenization_verified',providerTransactionId:tx.id||null,authorizationCode:auth.authorization_code,refundQueued:!!(refund.ok&&rd.status),refundResponse:rd.message||null,updatedAt:admin.firestore.FieldValue.serverTimestamp()},{merge:true});
  return reply(res,200,{ok:true,enrolled:true,refundQueued:!!(refund.ok&&rd.status),message:refund.ok&&rd.status?'Card verified. The ₦50 verification refund has been queued and your selected plan will begin after the free trial.':'Card verified. Your free trial is active, but the verification refund could not be queued automatically; please contact support.'});
 }catch(e){console.error('Trial verify error',e);return reply(res,500,{ok:false,error:'Unable to complete billing setup.'})}
};
